### ISSUE TITLE
Issue syncing with modded moons

### ISSUE THREAD

**Issue by Pockett-Dev** [ovofnl/LC---Launch-Random#1]
Hey there,

I noticed this mod doesn't play nicely with any of Wesley's Modded moons: https://thunderstore.io/c/lethal-company/p/Magic_Wesley/Wesleys_Moons/

People are desynced from the host, the host launches to the correct planet while they are randomly given another planet. Could this be because the level isn't selected prior to launching? 

Awesome mod, just hopeful some capability will be added :D

**Comment by ovofnl** [comment]
> Hey there,
> 
> I noticed this mod doesn't play nicely with any of Wesley's Modded moons: https://thunderstore.io/c/lethal-company/p/Magic_Wesley/Wesleys_Moons/
> 
> People are desynced from the host, the host launches to the correct planet while they are randomly given another planet. Could this be because the level isn't selected prior to launching?
> 
> Awesome mod, just hopeful some capability will be added :D

Thanks for your comment, I will try to fix it as soon as possible. Now if want to go these moons, just disable these moons in configs, select these moons then let others put the lever XD.

**Comment by Pockett-Dev** [comment]
Okay! :) Do you think you could make it so the random moon selection occurs once you're in orbit rather than when you pull the lever to launch to the next moon? I wonder if that might fix this issue? 👀

**Comment by ovofnl** [comment]
I think it may not useless. It just like change a trigger method to do this random.

**Comment by ovofnl** [comment]
It may fixed in 1.3.0.

**Comment by Pockett-Dev** [comment]
Okay I will test and update here once I can confirm that this has been fixed or not :)

**Comment by Pockett-Dev** [comment]
I cannot start the game/launch the ship with the mod installed atm - here's a code to the profile I'm using: 018dfc74-4c21-31c2-fa3d-0cbd59b2f05e

**Comment by ovofnl** [comment]
It may be other mod have some bug that it cannot start the game. I disable my mod that it can not start the game/create the room too. Disable AdvancedCompany may resolve it.
It stuck in the start game that is the config have not correct. Make sure don't leave any blank, because I have not  do the null judge.

**Comment by Pockett-Dev** [comment]
Okay, testing again right now

Edit: I have a feeling I know what causes the game to not start with AdvancedCompany - it's probably the "Allowing players to join while landed" setting.

**Comment by Pockett-Dev** [comment]
I noticed that disabling LaunchRandom fixes the issue - is LR selecting a random level the moment you pull the lever? I wonder if that's causing an issue?

**Comment by ovofnl** [comment]
Try to reinstall Lethal Company. It may resolve this problem. It just like missing something files cause that.
I reinstall Lethal Company that I can create the room normally.
