### ISSUE TITLE
Issue with the update

### ISSUE THREAD

**Issue by GonnFR** [ovofnl/LC---Launch-Random#2]
Hello ovo, sorry to bother, i don't know if this is apropriate but the thing is, since 1.3.0 every update are an instant crash when we touch the lever of the ship, for everyone, maybe it's because of the pack we use, but maybe you could help ?
018e381e-e934-3dfd-6f63-e970e0067b21 is the R2modman code if you want to check by yourself, anyway, thank for the mod, and for your time.

**Comment by ovofnl** [comment]
I see that in config. Moons Settings Another - Moons Level(Except) is blank. Take it Default value or  "D" just ok. It will solve this problem. I will fix this in 1.3.4.

**Comment by GonnFR** [comment]
Oh yeah, thank you it work just fine. ^^
